In [2]:
import pandas as pd

In [9]:
athletes = pd.read_csv("athlete_events_post_1990.csv")
athletes.info()
athletes = athletes.rename(columns={"City":"GamesLocation","Team":"CountryRepresented"})
athletes.head()
#Sex, Medal
#Object --> String

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122216 entries, 0 to 122215
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      122216 non-null  int64
 1   Name    122216 non-null  object
 2   Sex     122216 non-null  object
 3   Age     122157 non-null  float64
 4   Height  116188 non-null  float64
 5   Weight  115753 non-null  float64
 6   Team    122216 non-null  object
 7   NOC     122216 non-null  object
 8   Games   122216 non-null  object
 9   Year    122216 non-null  int64
 10  Season  122216 non-null  object
 11  City    122216 non-null  object
 12  Sport   122216 non-null  object
 13  Event   122216 non-null  object
 14  Medal   16781 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 14.0+ MB

,ID,Name,Sex,Age,Height,Weight,CountryRepresented,NOC,Games,Year,Season,GamesLocation,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
3,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
4,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN

In [15]:
athletes["Sex"] = athletes["Sex"].astype("category")
athletes["Medal"] = athletes["Medal"].astype("category")
columns = ["Name","CountryRepresented","NOC","Games","Season","GamesLocation","Sport","Event"]
athletes[columns] = athletes[columns].astype("string")
athletes.head()

,ID,Name,Sex,Age,Height,Weight,CountryRepresented,NOC,Games,Year,Season,GamesLocation,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
3,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
4,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN